version: '3.9'
services:

  postgres-main:
    image: postgres:12.5
    container_name: postgres-main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test

  postgres-sh1:
    image: postgres:12.5
    container_name: postgres-sh1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test


  postgres-sh2:
    image: postgres:12.5
    container_name: postgres-sh2
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test

  postgres-sharding-app:
    image: postgres-sharding-app:latest
    container_name: postgres-sharding-app
    depends_on:
      - postgres-main
      - postgres-sh1
      - postgres-sh2
    ports:
      - "8080:8080"
